---
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-added-large-files

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"]

  - repo: local
    hooks:
      - id: cue-fmt
        name: cue-fmt
        entry: scripts/pre-commit-cue-fmt.sh
        language: script
        types: [cue]
        pass_filenames: true

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: 'v1.0.0-rc.1'
    hooks:
        # go imports also formats code like gofmt does
      - id: go-imports
        args: ["-w","-d=false"]
      - id: go-mod-tidy
      - id: go-vet-repo-mod
      - id: go-staticcheck-repo-mod
